### ISSUE TITLE
New version is out

### ISSUE THREAD

**Issue by hovancik** [flathub/net.hovancik.Stretchly#2]
@jwillikers I've made new Stretchly version, but not sure what I need to do :) 

I've updated https://github.com/hovancik/stretchly/blob/trunk/net.hovancik.Stretchly.metainfo.xml

What's of note is that Electron changed they Tray implementation: https://github.com/electron/electron/pull/36333 so I guess app indicator is not needed anymore?

**Comment by jwillikers** [comment]
@hovancik  Awesome. Congratulations on the release! The way things are set up, Flathub bot submits a PR automatically to update the Git tag of the Stretchly repository to the new one. It's already done this in PR #3. This should fail to build whenever the lockfile is updated. I'm still waiting for Flathub to improve their CI process to allow automatically updating the sources list, but for now, that needs to be manually updated by checking out the branch for the PR and running the [Update Instructions in the README](https://github.com/flathub/net.hovancik.Stretchly#update).

For the AppIndicator change, I should be able to remove the libappindicator library from the Flatpak. I'll also need to add additional permissions to allow access to the necessary DBus interface described in the [spec](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem). I'll do some testing on this locally and see how it works!

**Comment by hovancik** [comment]
Great! Thanks for helping :)

**Comment by jwillikers** [comment]
Your welcome! I had to tweak the DBus name ownership permissions, but I've got the app indicator working great under GNOME. The Flatpak should be updated automatically once the test builds for #3 complete successfully.

**Comment by hovancik** [comment]
I've released quick fix 1.13.1, will try to follow the update steps once new PR is created. Thanks again!
